// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {response} from '../models';
import {database} from '../models';
import {context} from '../models';

export function Connect(arg1:db.ConnectRequest):Promise<response.BaseResponse_rollingthunder_internal_db_ConnectResponse_>;

export function CountCollectionData(arg1:database.Table):Promise<response.BaseResponse_int_>;

export function CreateTable(arg1:database.Table,arg2:Array<database.ColumnDefinition>):Promise<response.BaseResponse_bool_>;

export function DeleteConnection(arg1:string):Promise<response.BaseResponse_bool_>;

export function DeleteRow(arg1:database.Table,arg2:string,arg3:any):Promise<response.BaseResponse_bool_>;

export function DropTable(arg1:database.Table):Promise<response.BaseResponse_bool_>;

export function ExecuteQuery(arg1:string):Promise<response.BaseResponse___map_string_interface____>;

export function GetCollectionData(arg1:database.Table):Promise<response.BaseResponse_rollingthunder_pkg_database_TableData_>;

export function GetCollectionStructures(arg1:database.Table):Promise<response.BaseResponse_rollingthunder_pkg_database_Structures_>;

export function GetCollections(arg1:Array<string>):Promise<response.BaseResponse___string_>;

export function GetDataTypes():Promise<response.BaseResponse___rollingthunder_pkg_database_DataType_>;

export function GetDatabaseInfo():Promise<response.BaseResponse_rollingthunder_pkg_database_Info_>;

export function GetIndices(arg1:database.Table):Promise<response.BaseResponse_rollingthunder_pkg_database_Indices_>;

export function GetSavedConnections():Promise<response.BaseResponse___rollingthunder_internal_db_SavedConnection_>;

export function GetSchemas():Promise<response.BaseResponse___string_>;

export function InsertRow(arg1:database.Table,arg2:Record<string, any>):Promise<response.BaseResponse_bool_>;

export function SaveConnection(arg1:database.Config):Promise<response.BaseResponse_rollingthunder_internal_db_SavedConnection_>;

export function Start(arg1:context.Context):Promise<void>;

export function TruncateTable(arg1:database.Table):Promise<response.BaseResponse_bool_>;

export function UpdateConnection(arg1:string,arg2:database.Config):Promise<response.BaseResponse_rollingthunder_internal_db_SavedConnection_>;

export function UpdateRow(arg1:database.Table,arg2:Record<string, any>,arg3:string):Promise<response.BaseResponse_bool_>;
