// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {response} from '../models';
import {db} from '../models';
import {diagnostics} from '../models';
import {context} from '../models';

export function ApplyDatabaseObjectChange(arg1:string,arg2:database.ApplyObjectChangeRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_ObjectChangeResult_>;

export function ApplyDatabaseRestore(arg1:database.ApplyRestoreRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_RestoreResult_>;

export function ApplySchemaMigration(arg1:database.ApplySchemaMigrationRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_SchemaMigrationResult_>;

export function ApplySecurityChange(arg1:string,arg2:database.ApplySecurityChangeRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_SecurityChangeResult_>;

export function ApplyTableChanges(arg1:string,arg2:database.TableChangeSet):Promise<response.BaseResponse_rollingthunder_pkg_database_TableChangeResult_>;

export function BackupDatabase(arg1:database.BackupRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_BackupResult_>;

export function BeginTransaction(arg1:string,arg2:string):Promise<response.BaseResponse_rollingthunder_internal_db_TransactionInfo_>;

export function CancelConnectionAttempt(arg1:string):Promise<response.BaseResponse_bool_>;

export function CancelDatabaseSession(arg1:database.CancelSessionRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_CancelSessionResult_>;

export function CancelExport(arg1:string):Promise<response.BaseResponse_bool_>;

export function CancelMaintenance(arg1:string):Promise<response.BaseResponse_bool_>;

export function CancelQuery(arg1:string):Promise<response.BaseResponse_bool_>;

export function CheckConnection(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_ConnectionHealth_>;

export function CheckForUpdates():Promise<response.BaseResponse_rollingthunder_internal_updater_CheckResult_>;

export function ChooseImportFile():Promise<response.BaseResponse_rollingthunder_pkg_database_ImportFileSelection_>;

export function ChooseRestoreFile(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_RestoreFileSelection_>;

export function ChooseSQLiteDatabaseFile(arg1:boolean):Promise<response.BaseResponse_string_>;

export function ClearConnectionPassword(arg1:string):Promise<response.BaseResponse_bool_>;

export function ClearConnectionSSHCredentials(arg1:string):Promise<response.BaseResponse_bool_>;

export function ClearDiagnostics():Promise<response.BaseResponse_bool_>;

export function CommitTransaction(arg1:string):Promise<response.BaseResponse_rollingthunder_internal_db_TransactionInfo_>;

export function Connect(arg1:db.ConnectRequest):Promise<response.BaseResponse_rollingthunder_internal_db_ConnectResponse_>;

export function ConnectSavedConnection(arg1:string,arg2:string):Promise<response.BaseResponse_rollingthunder_internal_db_ConnectResponse_>;

export function ConnectWithProfile(arg1:string,arg2:database.Config,arg3:string):Promise<response.BaseResponse_rollingthunder_internal_db_ConnectResponse_>;

export function CountCollectionData(arg1:string,arg2:database.Table):Promise<response.BaseResponse_int_>;

export function CreateTable(arg1:string,arg2:database.Table,arg3:Array<database.ColumnDefinition>):Promise<response.BaseResponse_bool_>;

export function DeleteConnection(arg1:string):Promise<response.BaseResponse_bool_>;

export function DeleteRow(arg1:string,arg2:database.Table,arg3:string,arg4:any):Promise<response.BaseResponse_bool_>;

export function DisconnectConnection(arg1:string):Promise<response.BaseResponse_bool_>;

export function DropTable(arg1:string,arg2:database.Table):Promise<response.BaseResponse_bool_>;

export function ExecuteQuery(arg1:database.QueryRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_QueryResult_>;

export function ExplainQuery(arg1:database.QueryRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_ExplainPlan_>;

export function ExportDiagnostics():Promise<response.BaseResponse_rollingthunder_internal_diagnostics_ExportResult_>;

export function ExportQueryResults(arg1:database.RowsExportRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_ExportResult_>;

export function ExportTableData(arg1:string,arg2:database.TableExportRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_ExportResult_>;

export function GetActiveConnections():Promise<response.BaseResponse___rollingthunder_internal_db_ConnectionInfo_>;

export function GetBackupCapabilities(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_BackupCapabilities_>;

export function GetCapabilities(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_Capabilities_>;

export function GetCollectionData(arg1:string,arg2:database.Table):Promise<response.BaseResponse_rollingthunder_pkg_database_TableData_>;

export function GetCollectionStructures(arg1:string,arg2:database.Table):Promise<response.BaseResponse_rollingthunder_pkg_database_Structures_>;

export function GetCollections(arg1:string,arg2:Array<string>):Promise<response.BaseResponse___string_>;

export function GetConnectionHealth(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_ConnectionHealth_>;

export function GetConnectionHealths():Promise<response.BaseResponse___rollingthunder_pkg_database_ConnectionHealth_>;

export function GetDataTypes(arg1:string):Promise<response.BaseResponse___rollingthunder_pkg_database_DataType_>;

export function GetDatabaseActivity(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_DatabaseActivity_>;

export function GetDatabaseInfo(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_Info_>;

export function GetDatabaseObject(arg1:string,arg2:database.ObjectReference):Promise<response.BaseResponse_rollingthunder_pkg_database_ObjectDetail_>;

export function GetDatabaseObjects(arg1:string,arg2:database.ObjectFilter):Promise<response.BaseResponse___rollingthunder_pkg_database_DatabaseObject_>;

export function GetDiagnosticsSettings():Promise<response.BaseResponse_rollingthunder_internal_diagnostics_Settings_>;

export function GetExportProgress(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_ExportProgress_>;

export function GetIndices(arg1:string,arg2:database.Table):Promise<response.BaseResponse_rollingthunder_pkg_database_Indices_>;

export function GetMaintenanceProgress(arg1:string):Promise<response.BaseResponse_rollingthunder_pkg_database_MaintenanceProgress_>;

export function GetSavedConnections():Promise<response.BaseResponse___rollingthunder_internal_db_SavedConnection_>;

export function GetSchemas(arg1:string):Promise<response.BaseResponse___string_>;

export function GetSecurityOverview(arg1:string,arg2:string,arg3:string):Promise<response.BaseResponse_rollingthunder_pkg_database_SecurityOverview_>;

export function GetTableDDL(arg1:string,arg2:database.Table):Promise<response.BaseResponse_string_>;

export function ImportData(arg1:database.ImportRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_ImportResult_>;

export function InsertRow(arg1:string,arg2:database.Table,arg3:Record<string, any>):Promise<response.BaseResponse_bool_>;

export function InspectImportFile(arg1:database.ImportPreviewRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_ImportPreview_>;

export function PreviewDatabaseObjectChange(arg1:string,arg2:database.ObjectChangeRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_ObjectChangePreview_>;

export function PreviewDatabaseRestore(arg1:database.RestorePreviewRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_RestorePreview_>;

export function PreviewSchemaMigration(arg1:database.SchemaMigrationRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_SchemaMigrationPreview_>;

export function PreviewSecurityChange(arg1:string,arg2:database.SecurityChangeRequest):Promise<response.BaseResponse_rollingthunder_pkg_database_SecurityChangePreview_>;

export function ReconnectConnection(arg1:string,arg2:string):Promise<response.BaseResponse_rollingthunder_pkg_database_ConnectionHealth_>;

export function RecordFrontendError(arg1:diagnostics.FrontendReport):Promise<response.BaseResponse_bool_>;

export function RollbackTransaction(arg1:string):Promise<response.BaseResponse_rollingthunder_internal_db_TransactionInfo_>;

export function SaveConnection(arg1:database.Config):Promise<response.BaseResponse_rollingthunder_internal_db_SavedConnection_>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;

export function SwitchConnection(arg1:string):Promise<response.BaseResponse_bool_>;

export function TruncateTable(arg1:string,arg2:database.Table):Promise<response.BaseResponse_bool_>;

export function UpdateConnection(arg1:string,arg2:database.Config):Promise<response.BaseResponse_rollingthunder_internal_db_SavedConnection_>;

export function UpdateDiagnosticsSettings(arg1:diagnostics.Settings):Promise<response.BaseResponse_rollingthunder_internal_diagnostics_Settings_>;

export function UpdateRow(arg1:string,arg2:database.Table,arg3:Record<string, any>,arg4:string):Promise<response.BaseResponse_bool_>;
