// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['db']['Service']['Connect'](arg1);
}

export function GetCollectionStructures(arg1) {
  return window['go']['db']['Service']['GetCollectionStructures'](arg1);
}

export function GetCollections(arg1) {
  return window['go']['db']['Service']['GetCollections'](arg1);
}

export function GetDatabaseInfo() {
  return window['go']['db']['Service']['GetDatabaseInfo']();
}

export function GetIndices(arg1) {
  return window['go']['db']['Service']['GetIndices'](arg1);
}

export function GetSchemas() {
  return window['go']['db']['Service']['GetSchemas']();
}

export function Start(arg1) {
  return window['go']['db']['Service']['Start'](arg1);
}
