// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDatabaseObjectChange(arg1, arg2) {
  return window['go']['db']['Service']['ApplyDatabaseObjectChange'](arg1, arg2);
}

export function ApplyTableChanges(arg1, arg2) {
  return window['go']['db']['Service']['ApplyTableChanges'](arg1, arg2);
}

export function BeginTransaction(arg1, arg2) {
  return window['go']['db']['Service']['BeginTransaction'](arg1, arg2);
}

export function CancelConnectionAttempt(arg1) {
  return window['go']['db']['Service']['CancelConnectionAttempt'](arg1);
}

export function CancelExport(arg1) {
  return window['go']['db']['Service']['CancelExport'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['db']['Service']['CancelQuery'](arg1);
}

export function CheckConnection(arg1) {
  return window['go']['db']['Service']['CheckConnection'](arg1);
}

export function CheckForUpdates() {
  return window['go']['db']['Service']['CheckForUpdates']();
}

export function ChooseImportFile() {
  return window['go']['db']['Service']['ChooseImportFile']();
}

export function ChooseSQLiteDatabaseFile(arg1) {
  return window['go']['db']['Service']['ChooseSQLiteDatabaseFile'](arg1);
}

export function ClearConnectionPassword(arg1) {
  return window['go']['db']['Service']['ClearConnectionPassword'](arg1);
}

export function ClearDiagnostics() {
  return window['go']['db']['Service']['ClearDiagnostics']();
}

export function CommitTransaction(arg1) {
  return window['go']['db']['Service']['CommitTransaction'](arg1);
}

export function Connect(arg1) {
  return window['go']['db']['Service']['Connect'](arg1);
}

export function ConnectSavedConnection(arg1, arg2) {
  return window['go']['db']['Service']['ConnectSavedConnection'](arg1, arg2);
}

export function ConnectWithProfile(arg1, arg2, arg3) {
  return window['go']['db']['Service']['ConnectWithProfile'](arg1, arg2, arg3);
}

export function CountCollectionData(arg1, arg2) {
  return window['go']['db']['Service']['CountCollectionData'](arg1, arg2);
}

export function CreateTable(arg1, arg2, arg3) {
  return window['go']['db']['Service']['CreateTable'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['db']['Service']['DeleteConnection'](arg1);
}

export function DeleteRow(arg1, arg2, arg3, arg4) {
  return window['go']['db']['Service']['DeleteRow'](arg1, arg2, arg3, arg4);
}

export function DisconnectConnection(arg1) {
  return window['go']['db']['Service']['DisconnectConnection'](arg1);
}

export function DropTable(arg1, arg2) {
  return window['go']['db']['Service']['DropTable'](arg1, arg2);
}

export function ExecuteQuery(arg1) {
  return window['go']['db']['Service']['ExecuteQuery'](arg1);
}

export function ExplainQuery(arg1) {
  return window['go']['db']['Service']['ExplainQuery'](arg1);
}

export function ExportDiagnostics() {
  return window['go']['db']['Service']['ExportDiagnostics']();
}

export function ExportQueryResults(arg1) {
  return window['go']['db']['Service']['ExportQueryResults'](arg1);
}

export function ExportTableData(arg1, arg2) {
  return window['go']['db']['Service']['ExportTableData'](arg1, arg2);
}

export function GetActiveConnections() {
  return window['go']['db']['Service']['GetActiveConnections']();
}

export function GetCapabilities(arg1) {
  return window['go']['db']['Service']['GetCapabilities'](arg1);
}

export function GetCollectionData(arg1, arg2) {
  return window['go']['db']['Service']['GetCollectionData'](arg1, arg2);
}

export function GetCollectionStructures(arg1, arg2) {
  return window['go']['db']['Service']['GetCollectionStructures'](arg1, arg2);
}

export function GetCollections(arg1, arg2) {
  return window['go']['db']['Service']['GetCollections'](arg1, arg2);
}

export function GetConnectionHealth(arg1) {
  return window['go']['db']['Service']['GetConnectionHealth'](arg1);
}

export function GetConnectionHealths() {
  return window['go']['db']['Service']['GetConnectionHealths']();
}

export function GetDataTypes(arg1) {
  return window['go']['db']['Service']['GetDataTypes'](arg1);
}

export function GetDatabaseInfo(arg1) {
  return window['go']['db']['Service']['GetDatabaseInfo'](arg1);
}

export function GetDatabaseObject(arg1, arg2) {
  return window['go']['db']['Service']['GetDatabaseObject'](arg1, arg2);
}

export function GetDatabaseObjects(arg1, arg2) {
  return window['go']['db']['Service']['GetDatabaseObjects'](arg1, arg2);
}

export function GetDiagnosticsSettings() {
  return window['go']['db']['Service']['GetDiagnosticsSettings']();
}

export function GetExportProgress(arg1) {
  return window['go']['db']['Service']['GetExportProgress'](arg1);
}

export function GetIndices(arg1, arg2) {
  return window['go']['db']['Service']['GetIndices'](arg1, arg2);
}

export function GetSavedConnections() {
  return window['go']['db']['Service']['GetSavedConnections']();
}

export function GetSchemas(arg1) {
  return window['go']['db']['Service']['GetSchemas'](arg1);
}

export function GetTableDDL(arg1, arg2) {
  return window['go']['db']['Service']['GetTableDDL'](arg1, arg2);
}

export function ImportData(arg1) {
  return window['go']['db']['Service']['ImportData'](arg1);
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['db']['Service']['InsertRow'](arg1, arg2, arg3);
}

export function InspectImportFile(arg1) {
  return window['go']['db']['Service']['InspectImportFile'](arg1);
}

export function PreviewDatabaseObjectChange(arg1, arg2) {
  return window['go']['db']['Service']['PreviewDatabaseObjectChange'](arg1, arg2);
}

export function ReconnectConnection(arg1, arg2) {
  return window['go']['db']['Service']['ReconnectConnection'](arg1, arg2);
}

export function RecordFrontendError(arg1) {
  return window['go']['db']['Service']['RecordFrontendError'](arg1);
}

export function RollbackTransaction(arg1) {
  return window['go']['db']['Service']['RollbackTransaction'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['db']['Service']['SaveConnection'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['db']['Service']['Shutdown'](arg1);
}

export function Start(arg1) {
  return window['go']['db']['Service']['Start'](arg1);
}

export function SwitchConnection(arg1) {
  return window['go']['db']['Service']['SwitchConnection'](arg1);
}

export function TruncateTable(arg1, arg2) {
  return window['go']['db']['Service']['TruncateTable'](arg1, arg2);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['db']['Service']['UpdateConnection'](arg1, arg2);
}

export function UpdateDiagnosticsSettings(arg1) {
  return window['go']['db']['Service']['UpdateDiagnosticsSettings'](arg1);
}

export function UpdateRow(arg1, arg2, arg3, arg4) {
  return window['go']['db']['Service']['UpdateRow'](arg1, arg2, arg3, arg4);
}
